sudo: required

dist: bionic

services:
  - docker

matrix:
  include:
  - name: "C++ Env in Ubuntu 22.04"
    env: BUILD_TAG=22.04
  - name: "C++ Env in Ubuntu 20.04"
    env: BUILD_TAG=20.04
  - name: "C++ Env in Ubuntu 18.04"
    env: BUILD_TAG=18.04
  - name: "C++ Env in Ubuntu 16.04"
    env: BUILD_TAG=16.04
#  - name: "C++ Env in Ubuntu 14.04"
#    env: BUILD_TAG=14.04

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder
  - docker buildx inspect mybuilder --bootstrap
  - docker buildx ls
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.us-west-1.aliyuncs.com
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.cn-shanghai.aliyuncs.com
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.cn-hongkong.aliyuncs.com
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.eu-central-1.aliyuncs.com
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.me-east-1.aliyuncs.com
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.ap-southeast-2.aliyuncs.com

script:
  - |
    if [ $BUILD_TAG = '22.04' ]; then
      travis_wait 30 docker buildx build ubuntu/22.04 -t vistart/ubuntu-cpp:22.04 -t vistart/ubuntu-cpp:jammy -t vistart/ubuntu-cpp:latest \
      -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:22.04 -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:jammy -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:latest \
      -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:22.04 -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:jammy -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:latest \
      -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:22.04 -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:jammy -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:latest \
      -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:22.04 -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:jammy -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:latest \
      -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:22.04 -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:jammy -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:latest \
      --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '20.04' ]; then
      travis_wait 30 docker buildx build ubuntu/20.04 -t vistart/ubuntu-cpp:20.04 -t vistart/ubuntu-cpp:focal \
      -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:20.04 -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:focal \
      -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:20.04 -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:focal \
      -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:20.04 -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:focal \
      -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:20.04 -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:focal \
      -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:20.04 -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:focal \
      --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '18.04' ]; then
      travis_wait 30 docker buildx build ubuntu/18.04 -t vistart/ubuntu-cpp:18.04 -t vistart/ubuntu-cpp:bionic \
      -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:18.04 -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:bionic \
      -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:18.04 -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:bionic \
      -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:18.04 -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:bionic \
      -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:18.04 -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:bionic \
      -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:18.04 -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:bionic \
      --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '16.04' ]; then
      travis_wait 30 docker buildx build ubuntu/16.04 -t vistart/ubuntu-cpp:16.04 -t vistart/ubuntu-cpp:xenial \
      -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:16.04 -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:xenial \
      -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:16.04 -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:xenial \
      -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:16.04 -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:xenial \
      -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:16.04 -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:xenial \
      -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:16.04 -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:xenial \
      --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '14.04' ]; then
      travis_wait 30 docker buildx build ubuntu/14.04 -t vistart/ubuntu-cpp:14.04 -t vistart/ubuntu-cpp:trusty \
      -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:14.04 -t registry.cn-hongkong.aliyuncs.com/vistart_public/ubuntu-cpp:trusty \
      -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:14.04 -t registry.cn-shanghai.aliyuncs.com/vistart_public/ubuntu-cpp:trusty \
      -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:14.04 -t registry.eu-central-1.aliyuncs.com/vistart_public/ubuntu-cpp:trusty \
      -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:14.04 -t registry.me-east-1.aliyuncs.com/vistart_public/ubuntu-cpp:trusty \
      -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:14.04 -t registry.ap-southeast-2.aliyuncs.com/vistart_public/ubuntu-cpp:trusty \
      --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7 --pull --push
    fi
