sudo: required

services:
  - docker

script:
- cd php/php/apache && docker build . -t vistart/php:apache

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/php
