sudo: required

dist: bionic

services:
  - docker

matrix:
  include:
  - name: "JENKINS-CI 2.235 with BLUEOCEAN 1.23.1"
    env: BUILD_TAG=2.235-1.23.1

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update -qq
  - sudo apt-get -y -qq -o Dpkg::Options::="--force-confnew" install docker-ce
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder
  - docker buildx inspect mybuilder --bootstrap
  - docker buildx ls
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - |
    if [ $BUILD_TAG = '2.235-1.23.1' ]; then
      git clone -b release/1.23.1 https://github.com/jenkinsci/blueocean-plugin blueocean/blueocean-plugin-master
      chmod +x blueocean/blueocean-plugin-master/bin/build-in-docker.sh
      blueocean/blueocean-plugin-master/bin/build-in-docker.sh -m
      docker buildx build blueocean -f Dockerfile -t vistart/blueocean:1.23.1 -t vistart/blueocean:latest --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/386 --pull --push
    fi