sudo: required

services:
  - docker

script:
- docker build python/scrapy -t vistart/python:scrapy -t vistart/python:scrapy-latest

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/python
