sudo: required

services:
  - docker

language: python

python:
  - 3.7

matrix:
  include:
  - name: "CUDA 10.0 / 10.1 / 10.2 in ubuntu 20.04"
    env: BUILD_GROUP=ubuntu20.04
  - name: "CUDA 10.0 / 10.1 / 10.2 in ubuntu 18.04"
    env: BUILD_GROUP=ubuntu18.04
  - name: "CUDA 10.0 / 10.1 / 10.2 in ubuntu 16.04"
    env: BUILD_GROUP=ubuntu16.04
  - name: "CUDA 9.0 / 9.2 / 10.0 in ubuntu 14.04"
    env: BUILD_GROUP=ubuntu14.04

before_script:
  - pip install requests

script:
  - |
    if [ $BUILD_GROUP = 'ubuntu20.04' ]; then

        docker build cuda/ubuntu20.04/10.1/base -t vistart/cuda:10.1-base-ubuntu20.04
        docker build cuda/ubuntu20.04/10.1/runtime -t vistart/cuda:10.1-runtime-ubuntu20.04
        docker build cuda/ubuntu20.04/10.1/runtime/cudnn7 -t vistart/cuda:10.1-cudnn7-runtime-ubuntu20.04
        docker build cuda/ubuntu20.04/10.1/devel -t vistart/cuda:10.1-devel-ubuntu20.04
        docker build cuda/ubuntu20.04/10.1/devel/cudnn7 -t vistart/cuda:10.1-cudnn7-devel-ubuntu20.04
        docker build cuda/ubuntu20.04/10.1/devel/cudnn7/tensorrt6 -t vistart/cuda:10.1-cudnn7-tensorrt6-devel-ubuntu20.04

    elif [ $BUILD_GROUP = 'ubuntu18.04' ]; then

        docker build cuda/ubuntu18.04/10.2/base -t vistart/cuda:10.2-base-ubuntu18.04
        docker build cuda/ubuntu18.04/10.2/runtime -t vistart/cuda:10.2-runtime-ubuntu18.04
        docker build cuda/ubuntu18.04/10.2/runtime/cudnn7 -t vistart/cuda:10.2-cudnn7-runtime-ubuntu18.04
        docker build cuda/ubuntu18.04/10.2/devel -t vistart/cuda:10.2-devel-ubuntu18.04
        docker build cuda/ubuntu18.04/10.2/devel/cudnn7 -t vistart/cuda:10.2-cudnn7-devel-ubuntu18.04
        docker build cuda/ubuntu18.04/10.2/devel/cudnn7/tensorrt6 -t vistart/cuda:10.2-cudnn7-tensorrt6-devel-ubuntu18.04

        python download_googledrive.py "$GDRIVETRTDEB1804101FID" "cuda/ubuntu18.04/10.1/devel/cudnn7/tensorrt6/nv-tensorrt-repo-ubuntu1804-cuda10.1-trt6.0.1.5-ga-20190913_1-1_amd64.deb"
        docker build cuda/ubuntu18.04/10.1/base -t vistart/cuda:10.1-base-ubuntu18.04
        docker build cuda/ubuntu18.04/10.1/runtime -t vistart/cuda:10.1-runtime-ubuntu18.04
        docker build cuda/ubuntu18.04/10.1/runtime/cudnn7 -t vistart/cuda:10.1-cudnn7-runtime-ubuntu18.04
        docker build cuda/ubuntu18.04/10.1/devel -t vistart/cuda:10.1-devel-ubuntu18.04
        docker build cuda/ubuntu18.04/10.1/devel/cudnn7 -t vistart/cuda:10.1-cudnn7-devel-ubuntu18.04
        docker build cuda/ubuntu18.04/10.1/devel/cudnn7/tensorrt6 -t vistart/cuda:10.1-cudnn7-tensorrt6-devel-ubuntu18.04
    
        python download_googledrive.py "$GDRIVETRTDEB1804100FID" "cuda/ubuntu18.04/10.0/devel/cudnn7/tensorrt6/nv-tensorrt-repo-ubuntu1804-cuda10.0-trt6.0.1.5-ga-20190913_1-1_amd64.deb"
        docker build cuda/ubuntu18.04/10.0/base -t vistart/cuda:10.0-base-ubuntu18.04
        docker build cuda/ubuntu18.04/10.0/runtime -t vistart/cuda:10.0-runtime-ubuntu18.04
        docker build cuda/ubuntu18.04/10.0/runtime/cudnn7 -t vistart/cuda:10.0-cudnn7-runtime-ubuntu18.04
        docker build cuda/ubuntu18.04/10.0/devel -t vistart/cuda:10.0-devel-ubuntu18.04
        docker build cuda/ubuntu18.04/10.0/devel/cudnn7 -t vistart/cuda:10.0-cudnn7-devel-ubuntu18.04
        docker build cuda/ubuntu18.04/10.0/devel/cudnn7/tensorrt6 -t vistart/cuda:10.0-cudnn7-tensorrt6-devel-ubuntu18.04

    elif [ $BUILD_GROUP = 'ubuntu16.04' ]; then

        docker build cuda/ubuntu16.04/10.2/base -t vistart/cuda:10.2-base-ubuntu16.04
        docker build cuda/ubuntu16.04/10.2/runtime -t vistart/cuda:10.2-runtime-ubuntu16.04
        docker build cuda/ubuntu16.04/10.2/runtime/cudnn7 -t vistart/cuda:10.2-cudnn7-runtime-ubuntu16.04
        docker build cuda/ubuntu16.04/10.2/devel -t vistart/cuda:10.2-devel-ubuntu16.04
        docker build cuda/ubuntu16.04/10.2/devel/cudnn7 -t vistart/cuda:10.2-cudnn7-devel-ubuntu16.04
        docker build cuda/ubuntu16.04/10.2/devel/cudnn7/tensorrt6 -t vistart/cuda:10.2-cudnn7-tensorrt6-devel-ubuntu16.04

        python download_googledrive.py "$GDRIVETRTDEB1604101FID" "cuda/ubuntu16.04/10.1/devel/cudnn7/tensorrt6/nv-tensorrt-repo-ubuntu1604-cuda10.1-trt6.0.1.5-ga-20190913_1-1_amd64.deb"
        docker build cuda/ubuntu16.04/10.1/base -t vistart/cuda:10.1-base-ubuntu16.04
        docker build cuda/ubuntu16.04/10.1/runtime -t vistart/cuda:10.1-runtime-ubuntu16.04
        docker build cuda/ubuntu16.04/10.1/runtime/cudnn7 -t vistart/cuda:10.1-cudnn7-runtime-ubuntu16.04
        docker build cuda/ubuntu16.04/10.1/devel -t vistart/cuda:10.1-devel-ubuntu16.04
        docker build cuda/ubuntu16.04/10.1/devel/cudnn7 -t vistart/cuda:10.1-cudnn7-devel-ubuntu16.04
        docker build cuda/ubuntu16.04/10.1/devel/cudnn7/tensorrt6 -t vistart/cuda:10.1-cudnn7-tensorrt6-devel-ubuntu16.04
    
        python download_googledrive.py "$GDRIVETRTDEB1604100FID" "cuda/ubuntu16.04/10.0/devel/cudnn7/tensorrt6/nv-tensorrt-repo-ubuntu1604-cuda10.0-trt6.0.1.5-ga-20190913_1-1_amd64.deb"
        docker build cuda/ubuntu16.04/10.0/base -t vistart/cuda:10.0-base-ubuntu16.04
        docker build cuda/ubuntu16.04/10.0/runtime -t vistart/cuda:10.0-runtime-ubuntu16.04
        docker build cuda/ubuntu16.04/10.0/runtime/cudnn7 -t vistart/cuda:10.0-cudnn7-runtime-ubuntu16.04
        docker build cuda/ubuntu16.04/10.0/devel -t vistart/cuda:10.0-devel-ubuntu16.04
        docker build cuda/ubuntu16.04/10.0/devel/cudnn7 -t vistart/cuda:10.0-cudnn7-devel-ubuntu16.04
        docker build cuda/ubuntu16.04/10.0/devel/cudnn7/tensorrt6 -t vistart/cuda:10.0-cudnn7-tensorrt6-devel-ubuntu16.04

    elif [ $BUILD_GROUP = 'ubuntu14.04' ]; then

        docker build cuda/ubuntu14.04/10.1/base -t vistart/cuda:10.1-base-ubuntu14.04
        docker build cuda/ubuntu14.04/10.1/runtime -t vistart/cuda:10.1-runtime-ubuntu14.04
        docker build cuda/ubuntu14.04/10.1/runtime/cudnn7 -t vistart/cuda:10.1-cudnn7-runtime-ubuntu14.04
        docker build cuda/ubuntu14.04/10.1/devel -t vistart/cuda:10.1-devel-ubuntu14.04
        docker build cuda/ubuntu14.04/10.1/devel/cudnn7 -t vistart/cuda:10.1-cudnn7-devel-ubuntu14.04
        docker build cuda/ubuntu14.04/10.1/devel/cudnn7/tensorrt6 -t vistart/cuda:10.1-cudnn7-tensorrt6-devel-ubuntu14.04

        docker build cuda/ubuntu14.04/10.0/base -t vistart/cuda:10.0-base-ubuntu14.04
        docker build cuda/ubuntu14.04/10.0/runtime -t vistart/cuda:10.0-runtime-ubuntu14.04
        docker build cuda/ubuntu14.04/10.0/runtime/cudnn7 -t vistart/cuda:10.0-cudnn7-runtime-ubuntu14.04
        docker build cuda/ubuntu14.04/10.0/devel -t vistart/cuda:10.0-devel-ubuntu14.04
        docker build cuda/ubuntu14.04/10.0/devel/cudnn7 -t vistart/cuda:10.0-cudnn7-devel-ubuntu14.04
        docker build cuda/ubuntu14.04/10.0/devel/cudnn7/tensorrt6 -t vistart/cuda:10.0-cudnn7-tensorrt6-devel-ubuntu14.04

    fi

after_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker push vistart/cuda
