sudo: required

services:
  - docker

script:
- cd mmdetection/v0.5.7 && docker build . -t vistart/mmdetection:v0.5.7
- cd ../v0.6.0 && docker build . -t vistart/mmdetection:v0.6.0
- cd ../v1.0.0 && docker build . -t vistart/mmdetection:v1.0.0
- cd ../dev-master && docker build . -t vistart/mmdetection:latest

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/mmdetection
