sudo: required

dist: bionic

services:
  - docker

matrix:
  include:
  - name: "C++ Env in Ubuntu 20.04"
    env: BUILD_TAG=20.04
  - name: "C++ Env in Ubuntu 18.04"
    env: BUILD_TAG=18.04
  - name: "C++ Env in Ubuntu 16.04"
    env: BUILD_TAG=16.04
  - name: "C++ Env in Ubuntu 14.04"
    env: BUILD_TAG=14.04

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder
  - docker buildx inspect mybuilder --bootstrap
  - docker buildx ls
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.us-west-1.aliyuncs.com

script:
  - |
    if [ $BUILD_TAG = '20.04' ]; then
      docker buildx build ubuntu/20.04 -t vistart/ubuntu-cpp:20.04 -t vistart/ubuntu-cpp:focal -t vistart/ubuntu-cpp:latest -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:20.04 -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:focal -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:latest --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '18.04' ]; then
      docker buildx build ubuntu/20.04 --build-arg ubuntu=$BUILD_TAG -t vistart/ubuntu-cpp:18.04 -t vistart/ubuntu-cpp:bionic -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:18.04 -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:bionic --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '16.04' ]; then
      docker buildx build ubuntu/20.04 --build-arg ubuntu=$BUILD_TAG -t vistart/ubuntu-cpp:16.04 -t vistart/ubuntu-cpp:xenial -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:16.04 -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:xenial --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '14.04' ]; then
      docker buildx build ubuntu/20.04 --build-arg ubuntu=$BUILD_TAG -t vistart/ubuntu-cpp:14.04 -t vistart/ubuntu-cpp:trusty -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:14.04 -t registry.us-west-1.aliyuncs.com/vistart_public/ubuntu-cpp:trusty --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7 --pull --push
    fi
