sudo: required

dist: bionic

services:
  - docker

matrix:
  include:
  - name: "Ubuntu 20.04"
    env: BUILD_TAG=20.04
  - name: "Ubuntu 18.04"
    env: BUILD_TAG=18.04
  - name: "Ubuntu 16.04"
    env: BUILD_TAG=16.04
  - name: "Ubuntu 14.04"
    env: BUILD_TAG=14.04

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder
  - docker buildx inspect mybuilder --bootstrap
  - docker buildx ls
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - |
    if [ $BUILD_TAG = '20.04' ]; then
      docker buildx build ubuntu/20.04 -t vistart/ubuntu:20.04 -t vistart/ubuntu:focal -t vistart/ubuntu:latest --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '18.04' ]; then
      docker buildx build ubuntu/18.04 -t vistart/ubuntu:18.04 -t vistart/ubuntu:bionic --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '16.04' ]; then
      docker buildx build ubuntu/16.04 -t vistart/ubuntu:16.04 -t vistart/ubuntu:xenial --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push
    elif [ $BUILD_TAG = '14.04' ]; then
      docker buildx build ubuntu/14.04 -t vistart/ubuntu:trusty -t vistart/ubuntu:14.04 --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7 --pull --push
    fi
