sudo: required

services:
  - docker

matrix:
  include:
  - name: "Point Cloud Library 1.9.1 in Ubuntu 18.04"
    env: BUILD_TAG=1.9.1-ubuntu18.04
  - name: "Point Cloud Library 1.9.1 in Ubuntu 16.04"
    env: BUILD_TAG=1.9.1-ubuntu16.04

script:
  - |
    if [ $BUILD_TAG = '1.9.1-ubuntu18.04' ]; then
      docker build pcl/ubuntu18.04/1.9.1 -t vistart/pcl:1.9.1-ubuntu18.04
    elif [ $BUILD_TAG = '1.9.1-ubuntu16.04' ]; then
      docker build pcl/ubuntu16.04/1.9.1 -t vistart/pcl:1.9.1-ubuntu16.04
    fi

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/pcl
