sudo: false

dist: bionic

service:
    - docker

matrix: 
    include:
        - name: "Fetch Files"
          env: BUILD_GROUP=fetch-files

script:
    - |
      if [ $BUILD_GROUP = 'fetch-files' ]; then
        docker build . -t registry.cn-hongkong.aliyuncs.com/vistart_public/fetch_files:202008231911
      fi

after_script:
    - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.cn-hongkong.aliyuncs.com
    - docker push registry.cn-hongkong.aliyuncs.com/vistart_public/fetch_files