sudo: false

dist: bionic

service:
    - docker

matrix: 
    include:
        - name: "Fetch Files"
          env: BUILD_GROUP=fetch-files

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker buildx version
    - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
    - docker buildx create --use --name mybuilder
    - docker buildx inspect mybuilder --bootstrap
    - docker buildx ls
    - echo "$DOCKER_ALIYUN_VISTART_PASSWORD" | docker login --username "$DOCKER_ALIYUN_VISTART_USERNAME" --password-stdin registry.cn-hongkong.aliyuncs.com

script:
    - |
      if [ $BUILD_GROUP = 'fetch-files' ]; then
        docker buildx build . -t registry.cn-hongkong.aliyuncs.com/vistart_public/fetch_files:boost_1_73_0 --platform=linux/amd64,linux/arm64 --pull --push
      fi
