sudo: required

services:
  - docker

matrix:
  include:
  - name: "v0.5.7"
    env: BUILD_TAG=v0.5.7
  - name: "v0.6.0"
    env: BUILD_TAG=v0.6.0
  - name: "v1.0.0"
    env: BUILD_TAG=v1.0.0
  - name: "v2.2.0"
    env: BUILD_TAG=v2.2.0
  - name: "latest"
    env: BUILD_TAG=latest

script:
  - |
    if [ $BUILD_TAG = 'v0.5.7' ]; then
      nvidia-docker build mmdetection/v0.5.7 -t vistart/mmdetection:v0.5.7
    elif [ $BUILD_TAG = 'v0.6.0' ]; then
      nvidia-docker build mmdetection/v0.6.0 -t vistart/mmdetection:v0.6.0
    elif [ $BUILD_TAG = 'v1.0.0' ]; then
      nvidia-docker build mmdetection/v1.0.0 -t vistart/mmdetection:v1.0.0
    elif [ $BUILD_TAG = 'v2.2.0' ]; then
      nvidia-docker build mmdetection/v2.2.0 -t vistart/mmdetection:v2.2.0
    elif [ $BUILD_TAG = 'latest' ]; then
      nvidia-docker build mmdetection/dev-master -t vistart/mmdetection:latest
    fi

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/mmdetection
