sudo: required

services:
  - docker

script:
- cd ml/py36 && docker build . -t vistart/ml:py36

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/php
