sudo: required

services:
  - docker

matrix:
  include:
  - name: "PHP 7.2 on AMD64"
    env: BUILD_GROUP=php7.2
    arch: amd64
  - name: "PHP 7.3 on AMD64"
    env: BUILD_GROUP=php7.3
    arch: amd64
  - name: "PHP 7.4 on AMD64"
    env: BUILD_GROUP=php7.4
    arch: amd64
  - name: "LATEST on AMD64"
    env: BUILD_GROUP=php-latest
    arch: amd64
  - name: "PHP 7.2 on ARM64"
    env: BUILD_GROUP=php7.2
    arch: arm64
  - name: "PHP 7.3 on ARM64"
    env: BUILD_GROUP=php7.3
    arch: arm64
  - name: "PHP 7.4 on ARM64"
    env: BUILD_GROUP=php7.4
    arch: arm64
  - name: "LATEST on ARM64"
    env: BUILD_GROUP=php-latest
    arch: amd64

  allow_failures:
#    - name: "PHP 7.4"
    - name: "LATEST"

script:
- |
  if [ $BUILD_GROUP = 'php7.2' ]; then

    docker build php/apache -f php/apache/Dockerfile-7.2 --build-arg TAG=7.2-apache -t vistart/php:7.2-apache

  elif [ $BUILD_GROUP = 'php7.3' ]; then

    docker build php/apache -f php/apache/Dockerfile-7.2 --build-arg TAG=7.3-apache -t vistart/php:7.3-apache

  elif [ $BUILD_GROUP = 'php7.4' ]; then

    docker build php/apache --build-arg TAG=7.4-apache -t vistart/php:7.4-apache

  elif [ $BUILD_GROUP = 'php-latest' ]; then

    docker build php/apache --build-arg TAG=apache -t vistart/php:apache

  fi

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/php
