sudo: required

services:
  - docker

matrix:
  include:
  - name: "Tensorflow 1.15 with Python 2.7"
    env: BUILD_TAG=tf1.15-py27
  - name: "Tensorflow 1.15 with Python 3.6"
    env: BUILD_TAG=tf1.15-py36

script:
- docker pull vistart/cuda:10.0-cudnn7-devel-ubuntu18.04
- |
  if [ $BUILD_TAG = 'tf1.15-py27' ]; then
    docker build build_tensorflow/1.15.0/py27 -t vistart/build_tensorflow:1.15-py27
  elif [ $BUILD_TAG = 'tf1.15-py36' ]; then
    docker build build_tensorflow/1.15.0/py36 -t vistart/build_tensorflow:1.15-py36
  fi


after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/build_tensorflow
