sudo: required

services:
  - docker

script:
- cd elasticsearch/6.8.0 && docker build . -t vistart/elasticsearch:6.8.0
- cd ../7.1.0 && docker build . -t vistart/elasticsearch:7.1.0

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/elasticsearch
