sudo: required

services:
  - docker

script:
- cd ubuntu/16.04 && docker build . -t vistart/ubuntu:16.04
- cd ../18.04 && docker build . -t vistart/ubuntu:18.04

after_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker push vistart/ubuntu
