sudo: required

services:
  - docker

matrix:
  include:
  - name: "PHP 7.2 with APACHE2"
    env: BUILD_GROUP=php7.2-apache
  - name: "PHP 7.3 with APACHE2"
    env: BUILD_GROUP=php7.3-apache
  - name: "PHP 7.4 with APACHE2"
    env: BUILD_GROUP=php7.4-apache
  - name: "LATEST with APACHE2"
    env: BUILD_GROUP=php-apache
  - name: "PHP 7.2 CLI"
    env: BUILD_GROUP=php7.2-cli
  - name: "PHP 7.3 CLI"
    env: BUILD_GROUP=php7.3-cli
  - name: "PHP 7.4 CLI"
    env: BUILD_GROUP=php7.4-cli
  - name: "LATEST CLI"
    env: BUILD_GROUP=php-cli

  allow_failures:
#    - name: "PHP 7.4"
    - name: "LATEST with APACHE2"
    - name: "LATEST CLI"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder
  - docker buildx inspect mybuilder --bootstrap
  - docker buildx ls
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
- |
  if [ $BUILD_GROUP = 'php7.2-apache' ]; then

    docker buildx build php/apache -f php/apache/Dockerfile-7.2 -t vistart/php:7.2-apache --platform=linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php7.3-apache' ]; then

    docker buildx build php/apache -f php/apache/Dockerfile-7.2 --build-arg TAG=7.3-apache -t vistart/php:7.3-apache --platform=linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php7.4-apache' ]; then

    docker buildx build php/apache --build-arg TAG=7.4-apache -t vistart/php:7.4-apache --platform=linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php-apache' ]; then

    docker buildx build php/apache --build-arg TAG=apache -t vistart/php:apache --platform=linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php7.2-cli' ]; then

    docker buildx build php/cli -f php/cli/Dockerfile-7.2 -t vistart/php:7.2-cli --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php7.3-cli' ]; then

    docker buildx build php/cli -f php/cli/Dockerfile-7.2 --build-arg TAG=7.3-cli -t vistart/php:7.3-cli --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php7.4-cli' ]; then

    docker buildx build php/cli --build-arg TAG=7.4-apache -t vistart/php:7.4-cli --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push

  elif [ $BUILD_GROUP = 'php-cli' ]; then

    docker buildx build php/cli --build-arg TAG=apache -t vistart/php:cli --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/s390x --pull --push

  fi

