sudo: required

services:
  - docker

script:
- cd elasticsearch/6.7.2 && docker build . -t vistart/elasticsearch:6.7.2
- cd ../7.0.1 && docker build . -t vistart/elasticsearch:7.0.1

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/elasticsearch
