sudo: required

services:
  - docker

script:
- cd mmdetection/v0.5.7 && docker build . -t vistart/mmdetection:v0.5.7
- cd ../v0.6rc0 && docker build . -t vistart/mmdetection:v0.6rc0
- cd ../dev-master && docker build . -t vistart/mmdetection:latest

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/mmdetection
