sudo: required

services:
  - docker

script:
- cd elasticsearch/6.8.2 && docker build . -t vistart/elasticsearch:6.8.2
- cd ../7.2.1 && docker build . -t vistart/elasticsearch:7.2.1
- cd ../7.3.0 && docker build . -t vistart/elasticsearch:7.3.0
- cd ../7.3.1 && docker build . -t vistart/elasticsearch:7.3.1

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/elasticsearch
