sudo: required

services:
  - docker

script:
- cd pcl/ubuntu18.04/1.9.1 && docker build . -t vistart/pcl:1.9.1-ubuntu18.04
- cd ../../ubuntu16.04/1.9.1 && docker build . -t vistart/pcl:1.9.1-ubuntu16.04

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/pcl
