sudo: required

services:
  - docker

matrix:
  include:
  - name: "Python 3.6 with CUDA 10.0"
    env: BUILD_TAG=py36
  - name: "Python 3.6 with CUDA 10.1"
    env: BUILD_TAG=py36-cuda10.1
  - name: "Python 2.7 with CUDA 10.0"
    env: BUILD_TAG=py27
  - name: "Python 2.7 with CUDA 10.1"
    env: BUILD_TAG=py27-cuda10.1

script:
    - |
        if [ $BUILD_TAG = 'py36' ]; then
            docker build ml/py36 --build-arg TF_VERSION=1.15.0 -t vistart/ml:py36 -t vistart/ml:py36-tf1 -t vistart/ml:py36-cuda10.0 -t vistart/ml:py36-cuda10.0-tf1
            docker build ml/py36 --build-arg TF_VERSION=2.0.0 -t vistart/ml:py36-tf2 -t vistart/ml:py36-cuda10.0-tf2
        elif [ $BUILD_TAG = 'py36-cuda10.1' ]; then
            docker build ml/py36-cuda10.1 --build-arg TF_VERSION=1.15.0 -t vistart/ml:py36-cuda10.1 -t vistart/ml:py36-cuda10.1-tf1
            docker build ml/py36-cuda10.1 --build-arg TF_VERSION=2.0.0 -t vistart/ml:py36-cuda10.1-tf2
        elif [ $BUILD_TAG = 'py27' ]; then
            docker build ml/py27 --build-arg TF_VERSION=1.15.0 -t vistart/ml:py27 -t vistart/ml:py27-tf1 -t vistart/ml:py27-cuda10.0 -t vistart/ml:py27-cuda10.0-tf1
            docker build ml/py27 --build-arg TF_VERSION=2.0.0 -t vistart/ml:py27-tf2 -t vistart/ml:py27-cuda10.0-tf2
        elif [ $BUILD_TAG = 'py27-cuda10.1' ]; then
            docker build ml/py27-cuda10.1 --build-arg TF_VERSION=1.15.0 -t vistart/ml:py27-cuda10.1 -t vistart/ml:py27-cuda10.1-tf1
            docker build ml/py27-cuda10.1 --build-arg TF_VERSION=2.0.0 -t vistart/ml:py27-cuda10.1-tf2
        fi

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/ml
