sudo: required

services:
  - docker

matrix:
  include:
  - name: "Tensorflow with Python 3.6 & CUDA 10.0"
    env: BUILD_TAG=py36-cuda10.0
  - name: "Tensorflow with Python 3.8 & CUDA 10.0"
    env: BUILD_TAG=py38-cuda10.0
  - name: "Tensorflow with Python 3.6 & CUDA 10.1"
    env: BUILD_TAG=py36-cuda10.1
  - name: "Tensorflow with Python 3.8 & CUDA 10.1"
    env: BUILD_TAG=py38-cuda10.1
  - name: "Tensorflow with Python 3.6 & CUDA 10.2"
    env: BUILD_TAG=py36-cuda10.2
  - name: "Tensorflow with Python 3.8 & CUDA 10.2"
    env: BUILD_TAG=py38-cuda10.2
  - name: "Tensorflow with Python 3.6 & CUDA 11.0"
    env: BUILD_TAG=py36-cuda11.0
  - name: "Tensorflow with Python 3.8 & CUDA 11.0"
    env: BUILD_TAG=py38-cuda11.0

  allow_failures:
    - name: "Tensorflow with Python 3.8 & CUDA 10.0"
    - name: "Tensorflow with Python 3.8 & CUDA 10.1"
    - name: "Tensorflow with Python 3.8 & CUDA 10.2"
    - name: "Tensorflow with Python 3.8 & CUDA 11.0"

script:
- |
  if [ $BUILD_TAG = 'py36-cuda10.0' ]; then

    docker build . -f build_tensorflow/py36-cuda10.0/Dockerfile \
                 --build-arg TF_BRANCH=r1.15 \
                 -t vistart/build_tensorflow:py36-tf1 \
                 -t vistart/build_tensorflow:py36-cuda10.0-tf1
    docker build . -f build_tensorflow/py36-cuda10.0/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py36 \
                 -t vistart/build_tensorflow:py36-cuda10.0 \
                 -t vistart/build_tensorflow:py36-tf2 \
                 -t vistart/build_tensorflow:py36-cuda10.0-tf2

  elif [ $BUILD_TAG = 'py38-cuda10.0' ]; then

    # docker build . -f build_tensorflow/py38-cuda10.0/Dockerfile \
    #              --build-arg TF_BRANCH=r1.15 \
    #              -t vistart/build_tensorflow:py38-tf1 \
    #              -t vistart/build_tensorflow:py38-cuda10.0-tf1
    docker build . -f build_tensorflow/py38-cuda10.0/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py38 \
                 -t vistart/build_tensorflow:py38-cuda10.0 \
                 -t vistart/build_tensorflow:py38-tf2 \
                 -t vistart/build_tensorflow:py38-cuda10.0-tf2

  elif [ $BUILD_TAG = 'py36-cuda10.1' ]; then

    docker build . -f build_tensorflow/py36-cuda10.1/Dockerfile \
                 --build-arg TF_BRANCH=r1.15 \
                 -t vistart/build_tensorflow:py36-cuda10.1-tf1
    docker build . -f build_tensorflow/py36-cuda10.1/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py36-cuda10.1 \
                 -t vistart/build_tensorflow:py36-cuda10.1-tf2

  elif [ $BUILD_TAG = 'py38-cuda10.1' ]; then

    # docker build . -f build_tensorflow/py38-cuda10.1/Dockerfile \
    #              --build-arg TF_BRANCH=r1.15 \
    #              -t vistart/build_tensorflow:py38-cuda10.1-tf1
    docker build . -f build_tensorflow/py38-cuda10.1/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py38-cuda10.1 \
                 -t vistart/build_tensorflow:py38-cuda10.1-tf2

  elif [ $BUILD_TAG = 'py36-cuda10.2' ]; then

    docker build . -f build_tensorflow/py36-cuda10.2/Dockerfile \
                 --build-arg TF_BRANCH=r1.15 \
                 -t vistart/build_tensorflow:py36-cuda10.2-tf1
    docker build . -f build_tensorflow/py36-cuda10.2/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py36-cuda10.2 \
                 -t vistart/build_tensorflow:py36-cuda10.2-tf2 \
                 -t vistart/build_tensorflow:latest


  elif [ $BUILD_TAG = 'py38-cuda10.2' ]; then

    # docker build . -f build_tensorflow/py38-cuda10.2/Dockerfile \
    #              --build-arg TF_BRANCH=r1.15 \
    #              -t vistart/build_tensorflow:py38-cuda10.2-tf1
    docker build . -f build_tensorflow/py38-cuda10.2/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py38-cuda10.2 \
                 -t vistart/build_tensorflow:py38-cuda10.2-tf2 \
                 -t vistart/build_tensorflow:latest

  elif [ $BUILD_TAG = 'py36-cuda11.0' ]; then

    docker build . -f build_tensorflow/py36-cuda11.0/Dockerfile \
                 --build-arg TF_BRANCH=r1.15 \
                 -t vistart/build_tensorflow:py36-cuda11.0-tf1
    docker build . -f build_tensorflow/py36-cuda11.0/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py36-cuda11.0 \
                 -t vistart/build_tensorflow:py36-cuda11.0-tf2 \
                 -t vistart/build_tensorflow:latest


  elif [ $BUILD_TAG = 'py38-cuda11.0' ]; then

    # docker build . -f build_tensorflow/py38-cuda11.0/Dockerfile \
    #              --build-arg TF_BRANCH=r1.15 \
    #              -t vistart/build_tensorflow:py38-cuda11.0-tf1
    docker build . -f build_tensorflow/py38-cuda11.0/Dockerfile \
                 --build-arg TF_BRANCH=r2.3 \
                 --build-arg BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-installer-linux-x86_64.sh \
                 -t vistart/build_tensorflow:py38-cuda11.0 \
                 -t vistart/build_tensorflow:py38-cuda11.0-tf2 \
                 -t vistart/build_tensorflow:latest

  fi


after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push vistart/build_tensorflow
