name: php - Build and Deploy to Aliyun Container Registry

on:
  push:
    branches: [php]
  schedule:
    - cron: "00 22 6 * *"
  workflow_dispatch:

jobs:
  build_8_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cli, apache]
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_VISTART_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_VISTART_PASSWORD }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: php
          file: php/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          provenance: false
          sbom: false
          build-args: |
            TAG=8.1-${{ matrix.variant }}
            PHP_VERSION=8.1
          tags: |
            registry.cn-shanghai.aliyuncs.com/vistart_public/php:8.1-${{ matrix.variant }}
      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}

  build_8_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cli, apache]
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_VISTART_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_VISTART_PASSWORD }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: php
          file: php/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          provenance: false
          sbom: false
          build-args: |
            TAG=8.2-${{ matrix.variant }}
            PHP_VERSION=8.2
          tags: |
            registry.cn-shanghai.aliyuncs.com/vistart_public/php:8.2-${{ matrix.variant }}
      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}

  build_8_3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cli, apache]
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_VISTART_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_VISTART_PASSWORD }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: php
          file: php/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          provenance: false
          sbom: false
          build-args: |
            TAG=8.3-${{ matrix.variant }}
            PHP_VERSION=8.3
          tags: |
            registry.cn-shanghai.aliyuncs.com/vistart_public/php:8.3-${{ matrix.variant }}
      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}

  build_8_4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cli, apache]
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_VISTART_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_VISTART_PASSWORD }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: php
          file: php/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          provenance: false
          sbom: false
          build-args: |
            TAG=8.4-${{ matrix.variant }}
            PHP_VERSION=8.4
          tags: |
            registry.cn-shanghai.aliyuncs.com/vistart_public/php:8.4-${{ matrix.variant }}
      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}

  build_8_5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cli, apache]
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_VISTART_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_VISTART_PASSWORD }}
      - name: Login to Aliyun Container Registry Hongkong
        uses: docker/login-action@v4
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_VISTART_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_VISTART_PASSWORD }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: php
          file: php/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          provenance: false
          sbom: false
          build-args: |
            TAG=8.5-${{ matrix.variant }}
            PHP_VERSION=8.5
          tags: |
            registry.cn-shanghai.aliyuncs.com/vistart_public/php:8.5-${{ matrix.variant }}
            registry.cn-hongkong.aliyuncs.com/vistart_public/php:8.5-${{ matrix.variant }}
            registry.cn-shanghai.aliyuncs.com/vistart_public/php:${{ matrix.variant }}
            registry.cn-hongkong.aliyuncs.com/vistart_public/php:${{ matrix.variant }}
      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}